spring.application.name=resenas
server.port=8090

spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require

spring.datasource.username=postgres.bsqmacefyronbhcmjlri
spring.datasource.password=2zWED9Au8Kz76S7X

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect