spring.application.name=usuarios
server.port=8082

spring.datasource.url=jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.bsqmacefyronbhcmjlri
spring.datasource.password=2zWED9Au8Kz76S7X

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/