spring.application.name=pagos
server.port=8086


ms.usuarios.url=http://localhost:8082
ms.catalogo.url=http://localhost:8083
ms.biblioteca.url=http://localhost:8084

spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.bsqmacefyronbhcmjlri
spring.datasource.password=2zWED9Au8Kz76S7X

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
