eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
ms:
  biblioteca:
    url: ${MS_BIBLIOTECA_URL:http://localhost:8084}
  catalogo:
    url: ${MS_CATALOGO_URL:http://localhost:8083}
  usuarios:
    url: ${MS_USUARIOS_URL:http://localhost:8082}
server:
  forward-headers-strategy: framework
  port: 8086
spring:
  application:
    name: pagos
  datasource:
    password: 2zWED9Au8Kz76S7X
    url: jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.bsqmacefyronbhcmjlri
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    server:
      url: http://localhost:9090/pagos
  swagger-ui:
    operations-sorter: method
