

CREATE TABLE usuarios (
    id BIGSERIAL PRIMARY KEY,
    nickname VARCHAR(100) NOT NULL UNIQUE,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    saldo DOUBLE PRECISION NOT NULL DEFAULT 0,
    rol VARCHAR(50) NOT NULL DEFAULT 'USER',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE usuarios RENAME COLUMN contrasena TO password_hash;